name: "✨ Feat"
description: 새로운 기능 추가
title: "[Feat] "
labels: ["feat"]
body:
  - type: textarea
    id: description
    attributes:
      label: 🛩️ Description
      placeholder: ex) 로그인 페이지 UI 구현
    validations:
      required: true
  - type: textarea
    id: todos
    attributes:
      label: ☑️ Todos
      value: |
        - [ ]
